# -*- coding: utf-8 -*-
"""data_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukt0nPiHvBhDsMEINOJ6neDQNvpT2R0j
"""

"""
Data Cleaning Module
Functions to handle missing values, duplicates, data type correction, and outliers.
"""
import pandas as pd
import numpy as np

def handle_missing_values(df, num_strategy='median', cat_strategy='mode'):
    # Numeric columns
    num_cols = df.select_dtypes(include=np.number).columns
    for col in num_cols:
        if num_strategy == 'median':
            df[col].fillna(df[col].median(), inplace=True)
        elif num_strategy == 'mean':
            df[col].fillna(df[col].mean(), inplace=True)

    # Categorical columns
    cat_cols = df.select_dtypes(include='object').columns
    for col in cat_cols:
        if cat_strategy == 'mode':
            df[col].fillna(df[col].mode()[0], inplace=True)
    return df

def remove_duplicates(df):
    return df.drop_duplicates()

def remove_outliers_iqr(df, numeric_cols=None):
    if numeric_cols is None:
        numeric_cols = df.select_dtypes(include=np.number).columns
    for col in numeric_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        df = df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]
    return df