# -*- coding: utf-8 -*-
"""feature_engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukt0nPiHvBhDsMEINOJ6neDQNvpT2R0j
"""

"""
Feature Engineering Module
Includes encoding, feature selection, polynomial features.
"""
import pandas as pd
from sklearn.preprocessing import OneHotEncoder


def encode_categorical(df, drop_first=True):
    df_encoded = pd.get_dummies(df, drop_first=drop_first)
    return df_encoded


def select_features_by_correlation(df, target, threshold=0.1):
    corr = df.corr()[target].abs()
    important_features = corr[corr > threshold].index.drop(target)
    return df[important_features]