# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukt0nPiHvBhDsMEINOJ6neDQNvpT2R0j
"""

"""
Preprocessing Module
Train-test split and scaling utilities.
"""
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import joblib

def split_data(df, target, test_size=0.2, random_state=42, stratify=True):
    y = df[target]
    X = df.drop(target, axis=1)
    strat = y if stratify and y.nunique() < 10 else None
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=strat
    )
    return X_train, X_test, y_train, y_test


def scale_features(X_train, X_test, scaler=None, save_path=None):
    if scaler is None:
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
    else:
        X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    if save_path:
        joblib.dump(scaler, save_path)
    return X_train_scaled, X_test_scaled, scaler