# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukt0nPiHvBhDsMEINOJ6neDQNvpT2R0j
"""

"""
Utility functions for file operations and general helpers.
"""
import pandas as pd
import joblib

def save_csv(df, path):
    df.to_csv(path, index=False)

def load_csv(path):
    return pd.read_csv(path)

def save_model(model, path):
    joblib.dump(model, path)

def load_model(path):
    return joblib.load(path)